package com.megazone.ERPSystem_phase2_Backend.logistics.repository.inventory_management.inventory_adjustment;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class InventoryAdjustmentRepositoryCustomImpl implements InventoryAdjustmentRepositoryCustom {
}
