package com.megazone.ERPSystem_phase2_Backend.logistics.repository.inventory_management.warehouse_transfer;

public class WarehouseTransferRepositoryCustomImpl implements WarehouseTransferRepositoryCustom {
}
