package com.megazone.ERPSystem_phase2_Backend.financial.repository.basic_information_management.account_subject.AccountSubjectTransferMemo;

import com.megazone.ERPSystem_phase2_Backend.financial.model.basic_information_management.account_subject.AccountSubjectTransferMemo;
import org.springframework.data.jpa.repository.JpaRepository;

public interface AccountSubjectTransferMemoRepository extends JpaRepository<AccountSubjectTransferMemo, Long>, AccountSubjectTransferMemoRepositoryCustom {
}