-- INSERT INTO journal_entry (
--     name,
--     code,
--     transaction_type,
--     account_subject_code
-- ) VALUES
--       ('매출','1','Sales','404'),
--       ('매출채권','2','Sales','108'),
--       ('신용카드매출채권','3','Sales','120'),
--       ('매입','1','Purchase','153'),
--       ('매입채무','2','Purchase','251'),
--       ('신용카드매입채무','3','Purchase','253');