package com.megazone.ERPSystem_phase2_Backend.financial.repository.voucher_entry.sales_and_purchase_voucher_entry.resolvedSaleAndPurchaseVoucher;

public interface ResolvedSaleAndPurchaseVoucherRepositoryCustom {
}
