spring:
  application:
    name: ERPSystem-phase2-Backend # 애플리케이션 이름 설정
  datasource:
    url: jdbc:mysql://localhost:3306/erp?useSSL=false&serverTimezone=UTC # 데이터베이스 URL 설정 (MySQL 데이터베이스 연결)
    username: root # 데이터베이스 사용자 이름
    password: 1234 # 데이터베이스 사용자 비밀번호
  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 시작 시 Hibernate가 데이터베이스 스키마를 생성하도록 설정
    show-sql: true # SQL 쿼리를 콘솔에 출력하도록 설정
    defer-datasource-initialization: true # 데이터베이스 초기화를 지연시켜, 스키마 생성 후 데이터 초기화가 이루어지도록 설정
  web:
    resources:
      static-locations:
        - 'classpath:/static/' # 정적 리소스 위치 지정 (클래스패스 기준)
        - 'classpath:/public/' # 정적 리소스 위치 지정 (클래스패스 기준)
        - 'classpath:/resources/' # 정적 리소스 위치 지정 (클래스패스 기준)
        - 'classpath:/META-INF/resources/' # 정적 리소스 위치 지정 (클래스패스 기준)
        - 'file:src/main/frontend/dist/' # 정적 리소스 위치 지정 (파일 시스템 기준)
  sql:
    init:
      mode: always # 항상 SQL 초기화 모드를 사용하도록 설정
      data-locations:
        - classpath:initial-database/financial/account_subject/account_subject_structure.sql
        - classpath:initial-database/financial/account_subject/account_subject_nature.sql
        - classpath:initial-database/financial/account_subject/account_subject_Standard_financial_statement.sql
        - classpath:initial-database/financial/account_subject/account_subject.sql
        - classpath:initial-database/financial/account_subject/account_subject_cash_memo.sql
        - classpath:initial-database/financial/account_subject/account_subject_fixed_memo.sql
        - classpath:initial-database/financial/account_subject/account_subject_transfer_memo.sql
        - classpath:initial-database/financial/common/financial_bank.sql
        - classpath:initial-database/financial/client/client_liquor.sql
        - classpath:initial-database/financial/client/client_category.sql
        - classpath:initial-database/financial/bank_account/bank_account_type.sql
        - classpath:initial-database/financial/bank_account/financial_address.sql
        - classpath:initial-database/financial/common/financial_contact.sql
        - classpath:initial-database/financial/bank_account/financial_bank_account.sql
        - classpath:initial-database/financial/company/company_tax_office.sql
        - classpath:initial-database/financial/company/company_main_business.sql
        - classpath:initial-database/financial/company/company_address.sql
        - classpath:initial-database/financial/company/company_corporate_kind.sql
        - classpath:initial-database/financial/company/company_corporate_type.sql
        - classpath:initial-database/financial/company/company_representative.sql
        - classpath:initial-database/financial/company/company.sql
#        - classpath:initial-database/financial/credit_card/credit_card.sql
#        - classpath:initial-database/financial/unresolved_voucher.sql
        - classpath:initial-database/financial/vat_type.sql
        - classpath:initial-database/financial/journal_entry_type_setup.sql
        - classpath:initial-database/financial/journal_entry.sql


        - classpath:initial-database/logistics/warehouse.sql
        - classpath:initial-database/hr/employee.sql
        - classpath:initial-database/hr/users.sql
        - classpath:initial-database/logistics/product_group.sql
#        - classpath:initial-database/logistics/product.sql

        - classpath:initial-database/production/production_routing/processDetails.sql
        - classpath:initial-database/production/basic_data/workcenter.sql
        - classpath:initial-database/production/production_routing/productionRouting.sql
#        - classpath:initial-database/production/production_schedule/work_order_assign/workOrder.sql
#        - classpath:initial-database/production/production_schedule/work_order_assign/shiftType.sql

        - classpath:initial-database/logistics/product.sql

        - classpath:initial-database/production/resource_data/equipmentData.sql
        - classpath:initial-database/production/resource_data/maintenanceHistory.sql
#        - classpath:initial-database/production/resource_data/worker.sql
#        - classpath:initial-database/production/production_schedule/work_order_assign/workerAssignment.sql

logging:
  level:
    org.hibernate.SQL: DEBUG # Hibernate SQL 쿼리 로그 레벨 설정 (DEBUG)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Hibernate SQL 바인딩 로그 레벨 설정 (TRACE)
