  # values.yaml
  # 공통적으로 사용할 리소스 설정이 있으면 내용 작성
  # 통합 컨테이너 이미지 설정
  image:
    repository: myregistry/erp-system     # 이미지 위치 (예: Docker 레지스트리)
    tag: "1.0.0"                          # 이미지 태그
    pullPolicy: IfNotPresent

  # 파드 복제 수
  replicaCount: 1

  # 서비스 설정
  service:
    type: ClusterIP
    port: 80

  # 환경 변수 설정
  env:
    database_host: "erp-database"         # 통합 데이터베이스 호스트
    database_user: "erp_user"             # 데이터베이스 사용자
    database_password: "secure_password"  # 데이터베이스 비밀번호

  # 리소스 요청 및 제한
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi