package com.megazone.ERPSystem_phase2_Backend.financial.repository.voucher_entry.sales_and_purchase_voucher_entry.unresolveSaleAndPurchaseVoucher;

import com.megazone.ERPSystem_phase2_Backend.financial.model.voucher_entry.sales_and_purchase_voucher_entry.dto.UnresolvedSaleAndPurchaseVoucherDeleteDTO;

import java.util.List;

public interface UnresolvedSaleAndPurchaseVoucherRepositoryCustom {
    List<Long> deleteVoucherByManager(UnresolvedSaleAndPurchaseVoucherDeleteDTO dto);
}
