package com.megazone.ERPSystem_phase2_Backend.financial.repository.basic_information_management.account_subject.AccountSubjectStandardFinancialStatement;

public interface AccountSubjectStandardFinancialStatementRepositoryCustom {
}