package com.megazone.ERPSystem_phase2_Backend.production.repository.work_performance.goods_receipt.CompleteProduct;

public class CompleteProductRepositoryImpl implements CompleteProductRepositoryCustom{
}
