package com.megazone.ERPSystem_phase2_Backend.financial.repository.basic_information_management.account_subject.AccountSubjectStructure;

import com.megazone.ERPSystem_phase2_Backend.financial.model.basic_information_management.account_subject.AccountSubjectStructure;
import org.springframework.data.jpa.repository.JpaRepository;

public interface AccountSubjectStructureRepository extends JpaRepository<AccountSubjectStructure, Long>, AccountSubjectStructureRepositoryCustom {
}