package com.megazone.ERPSystem_phase2_Backend.financial.repository.basic_information_management.account_subject.AccountSubjectNature;

import com.megazone.ERPSystem_phase2_Backend.financial.model.basic_information_management.account_subject.AccountSubjectFixedMemo;
import com.megazone.ERPSystem_phase2_Backend.financial.model.basic_information_management.account_subject.AccountSubjectNature;
import org.springframework.data.jpa.repository.JpaRepository;

public interface AccountSubjectNatureRepository extends JpaRepository<AccountSubjectNature, Long>, AccountSubjectNatureRepositoryCustom {
}