package com.megazone.ERPSystem_phase2_Backend.financial.repository.basic_information_management.account_subject.AccountSubjectCashMemo;

import com.megazone.ERPSystem_phase2_Backend.financial.model.basic_information_management.account_subject.AccountSubjectCashMemo;
import org.springframework.data.jpa.repository.JpaRepository;

public interface AccountSubjectCashMemoRepository extends JpaRepository<AccountSubjectCashMemo, Long>, AccountSubjectCashMemoRepositoryCustom {
}