package com.megazone.ERPSystem_phase2_Backend.hr.model.hr_management.enums;

public enum PermissionName {
    READ_PRIVILEGES,
    WRITE_PRIVILEGES,
    DELETE_PRIVILEGES,
    UPDATE_PRIVILEGES,
    ADMIN_PRIVILEGES,
    CONFIGURE_PRIVILEGES,
    MANAGE_USERS,
    MANAGE_ROLES,
    VIEW_REPORTS,
    GENERATE_REPORTS,
    DOWNLOAD_REPORTS,
    VIEW_PROJECTS,
    MANAGE_PROJECTS,
    ASSIGN_TASKS,
    VIEW_TASKS,
    VIEW_FINANCIALS,
    MANAGE_BUDGETS,
    PROCESS_PAYMENTS,
    EXECUTE_ACTIONS,
    ACCESS_ADMIN_PANEL,
    VIEW_AUDIT_LOGS
}
